name: Deploy to Pibulus
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PI_IP }} # Your Tailscale IP
        username: pibulus
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/media/pibulus/passport/www/html"
